### PR TITLE
Update to Chef Server 12.6.0 / Chef Client 12.10.24

### PR DESCRIPTION
**Pull request by derks**

### CODE REVIEW

**Comment by joerg** [comment]
Hi,

You forgot to update the actual package installation. :-D This worked for me:

```
dpkg -i chef-server-core_12.6.0-1_amd64.deb chef_12.10.24-1_amd64.deb
```

Also, while you're at it and since it fits the update, could you change/fix the backup script. For the chef-server-ctl org-show the "-l" option does not exist. I don't know if it ever did, but now it is gone and the backup is complete even without this option:

```
...
for org in $(chef-server-ctl org-list) ; do
    chef-server-ctl org-show -F json $org > organizations/$org.json
    mkdir organizations/$org
...
```

Proof that this option does not exist:

```
root@f31774361fd7:/# chef-server-ctl org-show --help
knife opc org show ORGNAME
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    API Client Key
        --[no-]color                 Use colored output, defaults to enabled
    -c, --config CONFIG              The configuration file to use
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
        --[no-]fips                  Enable fips mode
    -F, --format FORMAT              Which format to use for output
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
        --print-after                Show the data after a destructive operation
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message
```

**Comment by derks** [comment]
Added/Updated.

**Comment by joerg** [comment]
Perfekt. Just tested this and it works like a charm.

**Comment by mpasternacki** [comment]
Updated to 12.18.14 on master; automatic upgrades are handled by chef-server-ctl upgrade as prescribed in chef's documentation; plugins are out of scope for this image. Other changes (remove `-l`, variables for versioning) went in from another PR.

**Pull request closed without merging**
