### PR TITLE
Update Chef Server Core 12.4.1 and Chef Client 12.7.2

### PR DESCRIPTION
**Pull request by derks**

### CODE REVIEW

**Comment by joerg** [comment]
Nice work. We just tested this and found that the backup script is broken with the latest chef server. For chef-server-ctl user-show and org-show the "-l" options do not exist any more. I am not sure what they did, but removing them seems to be safe....

**Comment by joerg** [comment]
I also just found, that "chef-server-ctl reindex" requires sed to be installed. I always thought that sed is installed on any system, but the ubuntu 14.04 image seems to be lacking it.

**Comment by mpasternacki** [comment]
Thank you!

**Comment by mpasternacki** [comment]
Regarding sed: plain `ubuntu:14.04` image seems to include it, at least as of today:

```
$ docker run -i -t --rm ubuntu:14.04 which sed
/bin/sed
```

**Pull request merged**
